# Generated by Django 5.1.6 on 2025-02-27 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_alter_evaluation_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartiesJouees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('duree', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tentatives', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partie jouée',
                'verbose_name_plural': 'Partie jouées',
                'ordering': ['date'],
            },
        ),
    ]
