# Generated by Django 5.1.6 on 2025-02-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_partiesjouees'),
    ]

    operations = [
        migrations.AddField(
            model_name='partiesjouees',
            name='terminee',
            field=models.BooleanField(default=False),
        ),
    ]
